# Generated by Django 4.1.1 on 2022-11-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='タイトル')),
                ('abstract', models.TextField(verbose_name='概要')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('published', models.BooleanField(verbose_name='公開')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboro.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='章番号')),
                ('title', models.CharField(max_length=80, verbose_name='章名')),
                ('body', models.TextField(verbose_name='本文')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboro.book', verbose_name='書籍')),
            ],
            options={
                'verbose_name': '章',
                'verbose_name_plural': '章',
                'ordering': ['number'],
            },
        ),
    ]
