# Generated by Django 4.1.1 on 2022-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(verbose_name='表示順')),
                ('name', models.CharField(max_length=80, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['display_order'],
            },
        ),
    ]
